title: Mounika Achchannagari # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Analyst with background in Software Development and Computer Science.
  <br><br>
  Tools: Python, SQL, Tableau, Excel 
  <br><br>
  <a href="https://www.linkedin.com/in/mounika-achchannagari/">LinkedIn Profile</a> 
  <a href="https://www.linkedin.com/in/mounika-achchannagari/">LinkedIn Profile</a>
  <a href="https://www.linkedin.com/in/mounika-achchannagari/">LinkedIn Profile</a>
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
# google_analytics: UA-000000-0 # your Google Analytics tracking ID here
